### ISSUE TITLE
can't get Scathelocke's Chest (Spellbook)

### ISSUE THREAD

**Issue by TaiVuong** [clintbellanger/flare-game#502] opened 2016-03-18 19:51 UTC
https://github.com/clintbellanger/flare-game/blob/master/mods/alpha_demo/maps/brothers_lair_ice_hall.txt#L497
Fix: change line 497
"requires_not_status=lb_ice_looted;lb_ice_key" --> "requires_not_status=lb_ice_key,lb_ice_looted"

**Comment by dorkster** [comment] 2016-03-18 22:00
I was not able to reproduce this bug. The fix you proposed should not actually do anything. Semicolons are treated exactly like commas when parsing values. Also, the order of statuses does not matter.

Regardless, your fix better fits the formatting (commas instead of semicolons) we use for status checks, so I have updated the map [here](1f823c57fe6831b0c7e73bbbde1ce90e60286600). If this fixes the bug for you, feel free to close this issue.

**Closed** 2016-03-19 18:44 UTC
